--1

SELECT DISTINCT AA.IDALUMNO
FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA NOT IN ('150212','130113');

--2

SELECT A.NOMBRE
FROM ASIGNATURA a 
WHERE A.CREDITOS > (SELECT A.CREDITOS
					FROM ASIGNATURA a
					WHERE UPPER(a.NOMBRE) LIKE 'SEGURIDAD VIAL');

--3

SELECT IDALUMNO
FROM ALUMNO_ASIGNATURA aa 
WHERE IDASIGNATURA = '150212'
INTERSECT 
SELECT IDALUMNO 
FROM ALUMNO_ASIGNATURA aa 
WHERE IDASIGNATURA = '130113';

--4

SELECT AA.IDALUMNO
FROM ALUMNO_ASIGNATURA aa 
WHERE aa.IDASIGNATURA IN ('150212','130113')
GROUP BY AA.IDALUMNO 
HAVING COUNT(DISTINCT AA.IDASIGNATURA) = 1; 

--5

SELECT a.nombre 
FROM ASIGNATURA a
WHERE a.IDTITULACION LIKE '130110'
AND a.COSTEBASICO > (SELECT AVG(NVL(a.COSTEBASICO,0)) FROM asignatura a WHERE a.IDTITULACION LIKE '130110');

--6

SELECT AA.IDALUMNO
FROM ALUMNO_ASIGNATURA aa 
WHERE NOT IN ('150212','130113');

--7 

SELECT aa.IDALUMNO
FROM alumno_asignatura aa
WHERE aa.idasignatura = '150212'
AND aa.idalumno NOT IN (
    SELECT idalumno FROM alumno_asignatura WHERE idasignatura = '130113'
);

--8

--9

SELECT p.dni, p.nombre
FROM persona p
WHERE P.DNI NOT IN(SELECT DNI FROM PROFESOR p2)
AND P.DNI NOT IN(SELECT DNI FROM ALUMNO a);


--10

SELECT a.nombre
FROM asignatura a
WHERE a.creditos = (
    SELECT MAX(a2.creditos) FROM asignatura a2
);


--11

SELECT a.nombre
FROM asignatura a
LEFT JOIN alumno_asignatura aa ON a.idasignatura = aa.idasignatura
WHERE aa.idalumno IS NULL;

--12 

SELECT P.CIUDAD 
FROM PERSONA p 
WHERE P.DNI IN (SELECT DNI FROM PROFESOR p2)
INTERSECT 
SELECT P3.CIUDAD 
FROM PERSONA p3 
WHERE P3.DNI IN (SELECT DNI FROM ALUMNO a);











