CREATE TABLE FABRICANTE
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	CONSTRAINT PK_FABRICANTE PRIMARY KEY(CODIGO)
);

CREATE TABLE PRODUCTO
(
	CODIGO NUMBER(10),
	NOMBRE VARCHAR2(100),
	PRECIO NUMBER(10,2),
	CODIGO_FABRICANTE NUMBER(10),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_PRODUCTO FOREIGN KEY(CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO)
);


CREATE SEQUENCE SEC_CODIGO_FAB
START WITH 1
INCREMENT BY 1;

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'ASUS');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'LENOVO');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'HEWLETT-PACKARD');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'SAMSUNG');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'SEAGATE');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'CRUCIAL');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'GIGABYTE');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'HUAWEI');

INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL,'XIAOMI');

SELECT * FROM FABRICANTE f ;


CREATE SEQUENCE SEC_CODIGO_PRODUCTO
START WITH 1
INCREMENT BY 1;

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'DISCO DURO SATA3 1TB',86.99,5);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'MEMORIA RAM DDR4 8GB',120,6);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'DISCO SSD 1 TB',150.99,4);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'GEFORCE GTX 1050TI',185,7);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'GEFORCE GTX 1080 XTREME',755,6);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'MONITOR 24 LED FULL HD',202,1);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'MONITOR 27 LED FULL HD',245.99,1);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'PORTATIL YOGA 520',559,2);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'PORTATIL IDEAPD 320',444,2);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'IMPRESORA HP DESKJET 3720',59.99,3);

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'IMPRESORA HP DESKJET PRO M26NW',180,3);

SELECT * FROM PRODUCTO p ;



-------------------------------------------------------------



INSERT INTO FABRICANTE
VALUES (SEC_CODIGO_FAB.NEXTVAL, 'NVIDIA');

/*INSERT INTO FABRICANTE (NOMBRE)
VALUES ('INTEL');        NO SE PUEDE CREAR YA QUE DEJARIA LA CLAVE PRIMARIA NULA Y NO PUEDE SERLO*/

INSERT INTO PRODUCTO
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL,'MEMORIA RAM DDR5 16GB', 110, 6);
/*
INSERT INTO PRODUCTO (NOMBRE, PRECIO, CODIGO_FABRICANTE)
VALUES ('PORTATIL ASUS TUF F15', 500, 2);         NO SE PUEDE CREAR YA QUE LA CLAVE PRIMARIA NO PUEDE SER NULA*/

DELETE FROM FABRICANTE f 
WHERE NOMBRE LIKE 'ASUS';        
 
ALTER TABLE PRODUCTO
DROP CONSTRAINT FK_PRODUCTO;

ALTER TABLE PRODUCTO 
ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY(CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO) ON DELETE CASCADE;
 
DELETE FROM FABRICANTE f 
WHERE NOMBRE LIKE 'XIAOMI';

UPDATE FABRICANTE 
SET CODIGO = 20
WHERE CODIGO = 2;

UPDATE FABRICANTE 
SET CODIGO = 30
WHERE CODIGO = 8;

UPDATE PRODUCTO 
SET PRECIO = PRECIO + 5;

DELETE FROM PRODUCTO p 
WHERE NOMBRE LIKE '%IMPRESORA%' AND PRECIO < 200;


CREATE VIEW PRODUCTO_MENOR50 AS
SELECT CODIGO, NOMBRE, PRECIO, CODIGO_FABRICANTE
FROM PRODUCTO
WHERE PRECIO < 50;

SELECT * FROM PRODUCTO_MENOR50 pm ;

INSERT INTO PRODUCTO p 
VALUES (SEC_CODIGO_PRODUCTO.NEXTVAL, 'MONITOR', 20, 30);

CREATE INDEX COD_NOM_FAB
ON PRODUCTO(NOMBRE, CODIGO_FABRICANTE);

























