CREATE TABLE EMPLEADO
(
	DNI VARCHAR2(12),
	NOMBRE VARCHAR2(40),
	SALARIO NUMBER(10),
	CONSTRAINT PK_EMP PRIMARY KEY(DNI)
);

CREATE TABLE ALERTA
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(20),
	SALARIO NUMBER(9),
	FECHA DATE,
	CONSTRAINT PK_ALERTA PRIMARY KEY(DNI)
);


CREATE OR REPLACE TRIGGER CONTROL_EMP
BEFORE INSERT OR UPDATE OR DELETE ON EMPLEADO
FOR EACH ROW
DECLARE
	Salario_Bajo EXCEPTION;
BEGIN
	IF INSERTING THEN
		IF :NEW.SALARIO > 5000 THEN
			INSERT INTO ALERTA (DNI, NOMBRE, SALARIO, FECHA)
			VALUES (:NEW.DNI, :NEW.NOMBRE, :NEW.SALARIO, SYSDATE);
		ELSIF :NEW.SALARIO < 1000 THEN
			RAISE Salario_Bajo;
		END IF;
	
	ELSIF UPDATING THEN
		IF :NEW.SALARIO > 5000 THEN
			INSERT INTO ALERTA (DNI, NOMBRE, SALARIO, FECHA)
			VALUES (:OLD.DNI, :OLD.NOMBRE, :NEW.SALARIO, SYSDATE); 
		ELSIF :NEW.SALARIO < 1000 THEN
			RAISE Salario_Bajo;
		ELSE
			DELETE FROM ALERTA a WHERE A.DNI LIKE :OLD.DNI;
		END IF;
	
	ELSE
		DELETE FROM ALERTA a WHERE A.DNI = :OLD.DNI;
	END IF;
	
EXCEPTION
	WHEN Salario_Bajo THEN
		RAISE_APPLICATION_ERROR(-20001, 'No trabajo gratis');
END;


INSERT INTO EMPLEADO e VALUES ('25521245L', 'MIGUELITO', 8000);
INSERT INTO EMPLEADO e VALUES ('25421245S', 'HASBULLA', 3000);
INSERT INTO EMPLEADO e VALUES ('25541245Z', 'MOHAMMAD', 4000);
INSERT INTO EMPLEADO e VALUES ('24521245K', 'PAJARO AZUL', 4999);

UPDATE EMPLEADO SET SALARIO = 9000
WHERE DNI LIKE '25541245Z';

DELETE FROM EMPLEADO e WHERE DNI LIKE '25541245Z';

SELECT * FROM EMPLEADO e ;
SELECT * FROM ALERTA a ;



