--1

SELECT c.NOMBRE, p.NOMBRE  FROM CLIENTES c , PUEBLOS p ;

--2 

SELECT P.NOMBRE, P2.NOMBRE FROM PUEBLOS p , PROVINCIAS p2 ;

--3 

SELECT C.NOMBRE, P.NOMBRE, P2.NOMBRE FROM CLIENTES c ,PUEBLOS p ,PROVINCIAS p2 ;

--4 

SELECT DISTINCT P.NOMBRE FROM PROVINCIAS p 

--5

SELECT DISTINCT A.DESCRIP FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON A.CODART = LF.CODART 
WHERE LF.CANT > 10;

--6 

SELECT F.FECHA,LF.CODART,LF.CANT FROM FACTURAS f
JOIN LINEAS_FAC lf ON F.CODFAC = LF.CODFAC 
ORDER BY F.FECHA DESC , LF.CODART ASC, LF.CANT DESC ;

--7

SELECT F.CODFAC, F.FECHA FROM FACTURAS f 
JOIN CLIENTES c ON F.CODCLI = C.CODCLI 
WHERE C.CODPOSTAL LIKE '%7%';

--8 

SELECT F.CODFAC, F.FECHA, C.NOMBRE FROM FACTURAS f 
JOIN CLIENTES c ON F.CODCLI = C.CODCLI ;

--9

SELECT F.CODFAC, F.FECHA, F.IVA, F.DTO, C.NOMBRE FROM FACTURAS f 
JOIN CLIENTES c ON F.CODCLI = C.CODCLI 
WHERE F.IVA IS NULL OR F.IVA = 0 OR F.DTO IS NULL;

--10

SELECT A.DESCRIP, A.PRECIO PRECIO_ACTUAL, LF.PRECIO PRECIO_VENDIDO FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON A.CODART = LF.CODART 
WHERE LF.PRECIO < A.PRECIO; 





