--1

SELECT c.NOMBRE, p.NOMBRE  FROM CLIENTES c , PUEBLOS p 
WHERE C.CODPUE = P.CODPUE ;

SELECT c.NOMBRE, p2.NOMBRE  FROM CLIENTES c
JOIN PUEBLOS p2 ON C.CODPUE = P2.CODPUE;

--2 

SELECT P.NOMBRE, P2.NOMBRE FROM PUEBLOS p , PROVINCIAS p2
WHERE P.CODPRO = P2.CODPRO ;

SELECT P.NOMBRE FROM PUEBLOS p 
JOIN PROVINCIAS p2 ON P.CODPRO = P2.CODPRO ;

--3 

SELECT C.NOMBRE, P.NOMBRE, P2.NOMBRE FROM CLIENTES c ,PUEBLOS p ,PROVINCIAS p2
WHERE C.CODPUE = P.CODPUE ;

SELECT C.NOMBRE FROM CLIENTES c 
JOIN PUEBLOS p ON C.CODPUE = P.CODPUE 
JOIN PROVINCIAS p2 ON P.CODPRO = P2.CODPRO;

--4 

SELECT DISTINCT P.NOMBRE FROM PROVINCIAS p
JOIN PUEBLOS p2 ON P.CODPRO = P2.CODPRO 
JOIN CLIENTES c ON C.CODPUE = P2.CODPUE;

--5

SELECT DISTINCT A.DESCRIP FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON A.CODART = LF.CODART 
WHERE LF.CANT > 10;

--6 

SELECT F.FECHA,LF.CODART,LF.CANT FROM FACTURAS f
JOIN LINEAS_FAC lf ON F.CODFAC = LF.CODFAC 
ORDER BY F.FECHA DESC , LF.CODART ASC, LF.CANT DESC ;

--7

SELECT F.CODFAC, F.FECHA FROM FACTURAS f 
JOIN CLIENTES c ON F.CODCLI = C.CODCLI 
WHERE C.CODPOSTAL LIKE '%7%';

--8 

SELECT F.CODFAC, F.FECHA, C.NOMBRE FROM FACTURAS f 
JOIN CLIENTES c ON F.CODCLI = C.CODCLI ;

--9

SELECT F.CODFAC, F.FECHA, F.IVA, F.DTO, C.NOMBRE FROM FACTURAS f 
JOIN CLIENTES c ON F.CODCLI = C.CODCLI 
WHERE (F.IVA IS NULL OR F.IVA = 0) OR F.DTO IS NULL;

--10

SELECT A.DESCRIP, A.PRECIO PRECIO_ACTUAL, LF.PRECIO PRECIO_VENDIDO FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON A.CODART = LF.CODART 
WHERE LF.PRECIO < A.PRECIO; 

--11

SELECT F.CODFAC,F.FECHA,F.IVA,F.DTO,A.DESCRIP,LF.PRECIO,LF.CANT,LF.DTO FROM FACTURAS f 
JOIN LINEAS_FAC lf ON F.CODFAC = LF.CODFAC 
JOIN ARTICULOS a ON LF.CODART = A.CODART;

--12

SELECT F.CODFAC,F.FECHA,F.IVA,F.DTO,A.DESCRIP,A.PRECIO,LF.CANT,LF.DTO,C.NOMBRE FROM FACTURAS f 
JOIN LINEAS_FAC lf ON F.CODFAC = LF.CODFAC 
JOIN ARTICULOS a ON LF.CODART = A.CODART
JOIN CLIENTES c ON C.CODCLI = F.CODCLI;

--13

SELECT C.NOMBRE FROM CLIENTES c 
JOIN PUEBLOS p ON C.CODPUE = P.CODPUE 
JOIN PROVINCIAS p2 ON P.CODPRO = P2.CODPRO 
WHERE P2.NOMBRE LIKE '%ma%';

--14

SELECT C.CODCLI FROM CLIENTES c 
JOIN FACTURAS f ON F.CODCLI = C.CODCLI 
JOIN LINEAS_FAC lf ON F.CODFAC = F.CODFAC 
JOIN ARTICULOS a ON LF.CODART = A.CODART
WHERE STOCK < STOCK_MIN ;

--15

SELECT DISTINCT A.DESCRIP FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON LF.CODART = A.CODART;

--16 

SELECT A.DESCRIP,(LF.PRECIO-LF.DTO) PRECIO_VENTA FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON LF.CODART = A.CODART; 

--17

SELECT A.DESCRIP FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON LF.CODART = A.CODART 
JOIN FACTURAS f ON F.CODFAC = LF.CODFAC 
JOIN CLIENTES c ON C.CODCLI = F.CODCLI 
JOIN PUEBLOS p ON P.CODPUE = C.CODPUE
JOIN PROVINCIAS p2 ON P2.CODPRO = P.CODPRO 
WHERE UPPER(P2.NOMBRE) LIKE '%A';

--18

SELECT DISTINCT C.NOMBRE FROM CLIENTES c 
JOIN FACTURAS f ON F.CODCLI = C.CODCLI 
WHERE F.DTO > 10;

--19

SELECT DISTINCT C.NOMBRE FROM CLIENTES c 
JOIN FACTURAS f ON F.CODCLI = C.CODCLI
JOIN LINEAS_FAC lf ON LF.CODFAC = F.CODFAC 
WHERE F.DTO > 10 OR LF.DTO >10;

--20

SELECT A.DESCRIP,LF.CANT,LF.PRECIO FROM ARTICULOS a 
JOIN LINEAS_FAC lf ON LF.CODART = A.CODART
JOIN FACTURAS f ON F.CODFAC = LF.CODFAC 
JOIN CLIENTES c ON C.CODCLI = F.CODCLI 
WHERE UPPER(C.NOMBRE) LIKE 'MARIA MERCEDES';





















