--1

SELECT A.IDASIGNATURA FROM ASIGNATURA a 

--2

SELECT P.NOMBRE, P.APELLIDO FROM PERSONA p 
JOIN PROFESOR p2 ON P.DNI = P2.DNI;

--3

SELECT A.NOMBRE FROM ASIGNATURA a 
JOIN PROFESOR p ON P.IDPROFESOR = A.IDPROFESOR 
JOIN PERSONA p2 ON P2.DNI = P.DNI 
WHERE UPPER(p2.CIUDAD) LIKE 'SEVILLA';

--4

SELECT P.NOMBRE,P.APELLIDO FROM PERSONA p  
JOIN ALUMNO a ON P.DNI = A.DNI;

--5

SELECT P.DNI,P.NOMBRE,P.APELLIDO FROM PERSONA p  
JOIN ALUMNO a ON P.DNI = A.DNI
WHERE UPPER(P.CIUDAD) LIKE 'SEVILLA';

--6

SELECT A.DNI,P.NOMBRE,P.APELLIDO FROM PERSONA p 
JOIN ALUMNO a ON A.DNI = P.DNI 
JOIN ALUMNO_ASIGNATURA aa ON AA.IDALUMNO = A.IDALUMNO 
JOIN ASIGNATURA a2 ON A2.IDASIGNATURA = AA.IDASIGNATURA 
WHERE UPPER(A2.NOMBRE) LIKE 'SEGURIDAD VIAL';

--7

SELECT DISTINCT A.IDTITULACION FROM ASIGNATURA a 
JOIN ALUMNO_ASIGNATURA aa ON AA.IDASIGNATURA = A.IDASIGNATURA 
JOIN ALUMNO a2 ON AA.IDALUMNO = A2.IDALUMNO 
WHERE A2.DNI LIKE '20202020A';

--8

SELECT A.NOMBRE FROM ASIGNATURA a 
JOIN PROFESOR p ON P.IDPROFESOR = A.IDPROFESOR 
JOIN PERSONA p2 ON P2.DNI = P.DNI
WHERE UPPER(P2.NOMBRE) LIKE '%ROSA%' AND UPPER(P2.APELLIDO) LIKE '%GARCIA%';

--9

SELECT ALUM.DNI  FROM ALUMNO ALUM
JOIN ALUMNO_ASIGNATURA aa ON ALUM.IDALUMNO = AA.IDALUMNO 
JOIN ASIGNATURA ASIG ON AA.IDASIGNATURA = ASIG.IDASIGNATURA 
JOIN PROFESOR PROF ON ASIG.IDPROFESOR = PROF.IDPROFESOR 
JOIN PERSONA P ON PROF.DNI = P.DNI 
WHERE UPPER(P.NOMBRE) LIKE 'JORGE' AND UPPER(P.APELLIDO) LIKE 'SAENZ';

-- 10

SELECT ALUM.DNI, p2.NOMBRE, p2.APELLIDO FROM ALUMNO ALUM
JOIN ALUMNO_ASIGNATURA aa ON ALUM.IDALUMNO = AA.IDALUMNO 
JOIN ASIGNATURA ASIG ON AA.IDASIGNATURA = ASIG.IDASIGNATURA 
JOIN PROFESOR PROF ON ASIG.IDPROFESOR = PROF.IDPROFESOR 
JOIN PERSONA P ON PROF.DNI = P.DNI
JOIN ALUMNO a ON A.IDALUMNO = AA.IDALUMNO 
JOIN PERSONA p2 ON p2.DNI = A.DNI 
WHERE UPPER(P.NOMBRE) LIKE 'JORGE' AND UPPER(P.APELLIDO) LIKE 'SAENZ';

-- 11

SELECT T.NOMBRE FROM TITULACION t 
JOIN ASIGNATURA a ON T.IDTITULACION = A.IDTITULACION 
WHERE A.CREDITOS = 4;

-- 12

SELECT A.NOMBRE, A.CREDITOS, T.NOMBRE FROM ASIGNATURA a 
JOIN TITULACION t ON A.IDTITULACION = T.IDTITULACION 
WHERE A.CUATRIMESTRE = 1;

-- 13

SELECT A.NOMBRE, A.COSTEBASICO, P.NOMBRE FROM ASIGNATURA a 
JOIN ALUMNO_ASIGNATURA aa ON A.IDASIGNATURA = AA.IDASIGNATURA 
JOIN ALUMNO a2 ON AA.IDALUMNO = A2.IDALUMNO 
JOIN PERSONA p ON A2.DNI = P.DNI 
WHERE A.CREDITOS > 4.5;

-- 14

SELECT P2.NOMBRE FROM PROFESOR p 
JOIN ASIGNATURA a ON P.IDPROFESOR = A.IDPROFESOR 
JOIN PERSONA p2 ON P.DNI = P2.DNI 
WHERE A.COSTEBASICO BETWEEN 25 AND 35;

-- 15

SELECT DISTINCT P.NOMBRE FROM PERSONA p 
JOIN ALUMNO a ON P.DNI = A.DNI 
JOIN ALUMNO_ASIGNATURA aa ON A.IDALUMNO = AA.IDALUMNO 
WHERE AA.IDASIGNATURA IN ('150212', '130113');

-- 16

SELECT A.NOMBRE, T.NOMBRE FROM ASIGNATURA a 
JOIN TITULACION t ON A.IDTITULACION = T.IDTITULACION 
WHERE A.CUATRIMESTRE = 2 AND A.CREDITOS != 6;

-- 17

SELECT A.NOMBRE, A.CREDITOS * 10 HORAS, A2.DNI FROM ASIGNATURA a 
JOIN ALUMNO_ASIGNATURA aa ON A.IDASIGNATURA = AA.IDASIGNATURA 
JOIN ALUMNO a2 ON AA.IDALUMNO = A2.IDALUMNO;

-- 18

SELECT P.NOMBRE FROM PERSONA p 
JOIN ALUMNO a ON P.DNI = A.DNI 
JOIN ALUMNO_ASIGNATURA aa ON A.IDALUMNO = AA.IDALUMNO 
WHERE UPPER(P.CIUDAD) LIKE 'SEVILLA' AND P.VARON = 0;

-- 19

SELECT A.NOMBRE FROM ASIGNATURA a 
WHERE A.CURSO = 1 AND A.IDPROFESOR = 'P101';

-- 20

SELECT p.NOMBRE FROM ALUMNO a 
JOIN PERSONA p ON P.DNI = A.DNI 
JOIN ALUMNO_ASIGNATURA aa ON A.IDALUMNO = AA.IDALUMNO 
WHERE aa.NUMEROMATRICULA >= 3;

























